# Generated by Django 3.1.2 on 2020-11-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(blank=True, db_column='Text_Area', max_length=150, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchName', models.CharField(default='', max_length=50)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClincName', models.CharField(max_length=50)),
                ('cereatedDate', models.DateField(auto_now_add=True, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('StartDdate', models.DateField(auto_now_add=True, null=True)),
                ('CloseDdate', models.DateField(blank=True, null=True)),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Comefrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComeFrom', models.CharField(blank=True, db_column='Text_ComeFrom', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=50)),
                ('DeviceFunction', models.CharField(max_length=50)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocName', models.CharField(blank=True, db_column='DocNameIN', default='New Doctor', max_length=150, null=True)),
                ('DocSpecialty', models.CharField(blank=True, db_column='DocSpecialty', default='', max_length=150, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocName', models.CharField(blank=True, db_column='DocNameOut', default='New Doctor', max_length=150, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(blank=True, db_column='Gender_Text', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JopName', models.CharField(blank=True, db_column='Text_Jop', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('PatientSecondName', models.CharField(blank=True, db_column='SecondName', max_length=50, null=True)),
                ('PatientThirdName', models.CharField(blank=True, db_column='ThirdName', max_length=50, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('PatientCode', models.CharField(blank=True, db_column='Pationt_Code', max_length=50, null=True)),
                ('PatientBbarcode', models.CharField(blank=True, db_column='Pationt_BarCode', max_length=50, null=True)),
                ('Birtdate', models.DateField(blank=True, null=True)),
                ('PlaceJop', models.CharField(blank=True, db_column='Place_Jop', max_length=150, null=True)),
                ('PatientMobile1', models.IntegerField(blank=True, null=True)),
                ('PatientMobile2', models.IntegerField(blank=True, null=True)),
                ('Area', models.ForeignKey(blank=True, db_column='Area', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Area', to='novav1.area')),
                ('ComeFrom', models.ForeignKey(blank=True, db_column='Id_ComeFrom', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novav1.comefrom')),
                ('Gender', models.ForeignKey(blank=True, db_column='Id_Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novav1.gender')),
                ('Jop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.jop')),
                ('JopArea', models.ForeignKey(blank=True, db_column='JopArea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='JopArea', to='novav1.area')),
                ('PatientFfriend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient')),
                ('doctor', models.ForeignKey(blank=True, db_column='Id_Doctor', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novav1.doctorout')),
            ],
        ),
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BodyPart', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('BallsNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stractuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StractuerPer', models.IntegerField(blank=True, db_column='Id_Stractuer_Per', null=True)),
                ('NameStractuer', models.IntegerField(blank=True, db_column='Name_Stractuer', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=50)),
                ('RoomActive', models.BooleanField(default=True)),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.branch', verbose_name='Branch Name')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateReservation', models.DateTimeField(auto_now_add=True, null=True)),
                ('FromTimeReservation', models.DateTimeField(blank=True, db_column='FromTime_Reservation', null=True)),
                ('ToTimeReservation', models.DateTimeField(blank=True, db_column='ToTime_Reservation', null=True)),
                ('Reservation', models.CharField(blank=True, db_column='Text_Reservation', max_length=350, null=True)),
                ('balance', models.FloatField()),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.branch')),
                ('Clinc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.clinc')),
                ('Doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.doctorin')),
                ('Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageName', models.CharField(max_length=50)),
                ('PackageNewPrice', models.FloatField()),
                ('OneBalcesPrice', models.FloatField(default=0)),
                ('CountBalces', models.FloatField(default=0)),
                ('Active', models.BooleanField(default=True)),
                ('PackageParts', models.ManyToManyField(related_name='PackageParts', to='novav1.pricing')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('stock_no', models.CharField(max_length=10)),
                ('description_short', models.CharField(max_length=150)),
                ('description_long', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('Active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novav1.category')),
            ],
        ),
        migrations.AddField(
            model_name='clinc',
            name='Device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.device'),
        ),
        migrations.AddField(
            model_name='clinc',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.room'),
        ),
    ]
